# Generated by Django 3.1.3 on 2020-12-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0004_samochod_wlasciciel_uzytkownik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='data_urodzenia',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='imie',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='zarobki',
            field=models.DecimalField(decimal_places=2, default=4000, max_digits=10, null=True),
        ),
    ]
